from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start6{CMD_INDEX}'
        self.MirrorCommand = f'mirror6{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirror6{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirror6{CMD_INDEX}'
        self.CancelMirror = f'cancel6{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall6{CMD_INDEX}'
        self.ListCommand = f'list6{CMD_INDEX}'
        self.SearchCommand = f'search6{CMD_INDEX}'
        self.StatusCommand = f'status6{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users6{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize6{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize6{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo6{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo6{CMD_INDEX}'
        self.PingCommand = f'ping6{CMD_INDEX}'
        self.RestartCommand = f'restart6{CMD_INDEX}'
        self.StatsCommand = f'stats6{CMD_INDEX}'
        self.HelpCommand = f'help6{CMD_INDEX}'
        self.LogCommand = f'log6{CMD_INDEX}'
        self.CloneCommand = f'clone6{CMD_INDEX}'
        self.CountCommand = f'count6{CMD_INDEX}'
        self.WatchCommand = f'watch6{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch6{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirror6{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror6{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirror6{CMD_INDEX}'
        self.DeleteCommand = f'del6{CMD_INDEX}'
        self.ShellCommand = f'shell6{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp6{CMD_INDEX}'
        self.LeechSetCommand = f'leechset6{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb6{CMD_INDEX}'
        self.LeechCommand = f'leech6{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech6{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech6{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech6{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech6{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech6{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch6{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch6{CMD_INDEX}'
        self.RssListCommand = f'rsslist6{CMD_INDEX}'
        self.RssGetCommand = f'rssget6{CMD_INDEX}'
        self.RssSubCommand = f'rsssub6{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub6{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset6{CMD_INDEX}'
        self.EvalCommand = f'eval6{CMD_INDEX}'
        self.ExecCommand = f'exec6{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals6{CMD_INDEX}'

BotCommands = _BotCommands()
